### ISSUE TITLE
Miss notifications on services not yet converged

### ISSUE THREAD

**Issue by hatched-DavidMichon** [docker-flow/docker-flow-swarm-listener#36]
I am facing an issue that might be related to how events are managed when scaling service.

When I asked for more replicas for my service and there's no suitable node because of insufficient memory, no notification is generated by DFSL. This is problematic because I would like that my `@replicas_running` alerts in alertmanager to be updated to reflect the change of expected replicas.

I can see however a service update events in the docker events API like this:

```
2018-11-13T13:28:55.244973820Z service update bo3sfovtc0om4gvf73suf3zxg (name=staging-cookbook_cookbook, replicas.new=3, replicas.old=1)
```

In this case I would expect DSFL to send a notification.

Note That if I increase service replicas and there's enough suitable nodes, DFSL send the notification correctly.

_Originally posted by @hatched-DavidMichon in https://github.com/docker-flow/docker-flow-swarm-listener/issues/28#issuecomment-438268022_

**Comment by thomasjpfan** [comment]
There was an update to DFSL that caused it to wait for services to converge before sending out notifications. This lead to DFP behaving better, since DFSL will only update DFP if the service is up.

I can see two options to adjust DFSL for your use case:

1. Set a flag in DFSL to NOT wait for services to converge before sending a notification.
2. Send a notification for when the number of replicas changed from the last known number of replicas. This would result in multiple create notifications for a service slowly coming up.

**Comment by hatched-DavidMichon** [comment]
I understand that for DFP to get the notification when the services converged is better. Of course this pose a problem for the `@replicas_running` [alert shortcuts](https://monitor.dockerflow.com/usage/#alertif-parameter-shortcuts).

I'm not sure the second option would cover my use case because what I need is the replicas parameter in the create notification to be the desired replicas and not the actual number of replicas up in the swarm. If my services cannot create a replica due to not enough resources, no create notification will be send.

Your first options, set a a flag to send the notification, with the desired number of replicas without waiting for service to converge actually works for me.

What about an option to send the desired replicas number in the create notifications?

**Comment by thomasjpfan** [comment]
Currently, DFSL only sends the desired number of replicas. From my understanding, the issue you have is when you increase the number of replicas, and there are no resources, DFM is not notified of the new desired number of replicas because the service did not converge.

Looking at the `@replicas_running` query, this may open up another option:

3. Send a CREATE notification when there is at least one replica running, then send anther one when the service converges.

This way DFP should be happy, since there is at least one service up, and DFM would work since the new desired replicas was sent to it.

**Comment by hatched-DavidMichon** [comment]
Yes this is exactly what happens, when I increase the number of replicas, and there are not enough resources, DFM is not notified of the new desired number of replicas because the service did not converge.

This 3rd option also works for my use case. This way the `@replicas_running` will receive the desired number of replicas as long as at least 1 service is created. I designed my nodes and placement in a way that I will at least have enough resource available for 1 replica of a service.

But I can imagine other use cases where a service need to be created with N replicas but there's not enough space nor for a single replica. This would be cool to have the `@replicas_running` alerts already set up correctly on DFM with the desired replicas. This ways if you create a flow to increase an auto-scaling group based on this alert, it will work.

So getting a create notification to DFM as soon as a service is created on the swarm seems a better option to cover most use case. Of course you have a better understanding of the implications down the line with DFM and DFP.

**Comment by thomasjpfan** [comment]
Hm, for DFSL to work for this use case, it looks like a create notification must be sent even before one service is up. A flag such as `DF_NOTIFY_CREATE_SERVICE_IMMEDIATELY` could be added activate this feature. This flag should be only be used with DFM and not DFP. Additionally, if this flag is set, there will be two notifications, one for sent immediately, and another sent when the service converges. The final notification should be sent because, the flexible label feature in DFM, relies on the IPs of the services after they converge.

What do you think?

**Comment by hatched-DavidMichon** [comment]
Ok, it makes sense, would be fantastic to have this flag! I actually only use DFM and rely on traefik for the proxy. Also if someone use DFP, there's always the option to configure 2 DFSL services, one only for DFM and the other for DFP.

Implementing this solve 100% my use case. I'm very grateful for your help, many thx!

**Comment by thomasjpfan** [comment]
Please try `dockerflow/docker-flow-swarm-listener:18.11.28-19` with `DF_NOTIFY_CREATE_SERVICE_IMMEDIATELY=true` and see if it resolves your issue.

**Comment by hatched-DavidMichon** [comment]
@thomasjpfan Thanks for the release. I'll test it next week and let you know the result.

**Comment by hatched-DavidMichon** [comment]
@thomasjpfan I confirmed your release solve my issue. That is awesome! Many thx!
